#---------------------------------------------------------------------------------
# Executable name
#---------------------------------------------------------------------------------
TARGET		:=  $(shell basename $(CURDIR))

#---------------------------------------------------------------------------------
# Source sub-folders
#---------------------------------------------------------------------------------
SUBFOLDERS	:=	audio collectables core data display enemies entities gl helpers \
				interface managers objects player states transitions weapons

#---------------------------------------------------------------------------------
# Compiler executables
#---------------------------------------------------------------------------------
CC		:=	i686-w64-mingw32-gcc
CXX		:=	i686-w64-mingw32-g++

SDL_ROOT_DIR :=	/usr/i686-w64-mingw32

#---------------------------------------------------------------------------------
# Options for code generation
#---------------------------------------------------------------------------------
CFLAGS	:=	`$(SDL_ROOT_DIR)/bin/sdl2-config --cflags` \
			-g -Wall -DGL_GLEXT_PROTOTYPES -mwin32
CXXFLAGS:=	$(CFLAGS) -std=c++11 -MD
LDFLAGS	:=	`$(SDL_ROOT_DIR)/bin/sdl2-config --libs` \
			-g -static-libgcc -static-libstdc++ -static

#---------------------------------------------------------------------------------
# Any extra libraries you wish to link with your project
#---------------------------------------------------------------------------------
LIBS	:=	-lmingw32 -lSDL2_mixer -lSDL2_image -lSDL2main -lSDL2 -lopengl32 -lglew32.dll -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lversion -luuid

#---------------------------------------------------------------------------------
# Source folders
#---------------------------------------------------------------------------------
BUILD		:=	build
SOURCES		:=	source external $(foreach dir,$(SUBFOLDERS),source/$(dir))
INCLUDES	:=	include external $(foreach dir,$(SUBFOLDERS),include/$(dir))

#---------------------------------------------------------------------------------
# Additional folders for libraries
#---------------------------------------------------------------------------------
LIBDIRS		:= 	

#---------------------------------------------------------------------------------
# Source files
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))

#---------------------------------------------------------------------------------
export OUTPUT	:=	$(CURDIR)/$(TARGET).exe

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir))

export CFILES	:=	$(sort $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c))))
export CPPFILES	:=	$(sort $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp))))

SOURCEFILES	:=	$(foreach dir,$(SOURCES),$(wildcard $(dir)/*.c)) \
				$(foreach dir,$(SOURCES),$(wildcard $(dir)/*.cpp))
HEADERFILES	:=	$(foreach dir,$(INCLUDES),$(wildcard $(dir)/*.h)) \
				$(foreach dir,$(INCLUDES),$(wildcard $(dir)/*.hpp))

#---------------------------------------------------------------------------------
# Use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
#---------------------------------------------------------------------------------
	export LD	:=	$(CC)
#---------------------------------------------------------------------------------
else
#---------------------------------------------------------------------------------
	export LD	:=	$(CXX)
#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------

export OFILES	:=	$(CPPFILES:.cpp=.o32) $(CFILES:.c=.o32)

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir))

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(CURDIR)/$(dir))

#---------------------------------------------------------------------------------
.PHONY: $(BUILD) clean run install uninstall
#------------------------------------------------------------------------------
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@make --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.windows

#---------------------------------------------------------------------------------
run:
	@echo running ...
	@wine $(TARGET).exe

#---------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) $(TARGET).exe
	
#---------------------------------------------------------------------------------
install:
	@cp -u $(TARGET) /usr/bin/$(TARGET)
	@echo installed.

#---------------------------------------------------------------------------------
uninstall:
	@rm -f /usr/bin/$(TARGET)
	@echo uninstalled.

#---------------------------------------------------------------------------------
else
#---------------------------------------------------------------------------------
# Makefile targets
#---------------------------------------------------------------------------------
all: $(OUTPUT)
	
#---------------------------------------------------------------------------------
$(OUTPUT): $(OFILES)
	@echo built ... $(notdir $@)
	@$(LD) $(LDFLAGS) $(OFILES) $(LIBPATHS) $(LIBS) -o $@

#---------------------------------------------------------------------------------
%.o32: %.c
	@echo $(notdir $<)
	@$(CC) $(CFLAGS) $(INCLUDE) -c $< -o $@
	
#---------------------------------------------------------------------------------
%.o32: %.cpp
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) $(INCLUDE) -c $< -o $@
	
-include *.d

#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------

